name: py_entitymatching_dev
channels:
  - conda-forge
  - uwmagellan
  - defaults
dependencies:
    - ipython == 5.6
    - matplotlib => 2.2.4
    - setuptools
    - py_stringsimjoin >= 0.3.0
    - cloudpickle
    - pyparsing
    - scikit-learn >= 0.18
    - pyqt
    - py_stringmatching
    - requests
    - cloudpickle
#    - xgboost
